# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e8086ee4aa14adcba50db3c94d3dc4ba"
name = "Ai Chatbot"
application_url = "https://specify-excessive-philippines-scored.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sushant-maha.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_product_listings,read_products,write_orders,write_products"

[auth]
redirect_urls = [
  "https://specify-excessive-philippines-scored.trycloudflare.com/auth/callback",
  "https://specify-excessive-philippines-scored.trycloudflare.com/auth/shopify/callback",
  "https://specify-excessive-philippines-scored.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
