# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2c97ca07b128aaddb018dd33c82e8946"
name = "Ai chatbot"
application_url = "https://marina-writes-medications-serious.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-80f0f545.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_product_listings,read_products,write_orders,write_products"

[auth]
redirect_urls = [
  "https://marina-writes-medications-serious.trycloudflare.com/auth/callback",
  "https://marina-writes-medications-serious.trycloudflare.com/auth/shopify/callback",
  "https://marina-writes-medications-serious.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
